name: Deploy
on:
  push:
    branches: master
  pull_request:
    branches: master
  schedule:
    - cron: "0 */6 * * *" # تشغيل كل 6 ساعات

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      id-token: write # Needed for auth with Deno Deploy
      contents: read # Needed to clone the repository
      actions: write # Needed to cancel other workflows

    steps:
      # Clone the repository
      - name: Clone repository
        uses: actions/checkout@v4

      # Install Node.js
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      # Install FFmpeg
      - name: Install FFmpeg
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      # Install dependencies
      - name: Install Dependencies
        run: npm install 
# Cancel Running Workflows Before npm start
      - name: Cancel Running Workflows Before Build
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}

      
      # Build the project
      - name: Build Project
        run: npm run start
